from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, Spacer
from reportlab.lib.enums import TA_CENTER


styles = getSampleStyleSheet()


def build_title():
    style = styles["Heading1"]
    style.alignment = TA_CENTER

    return [
        Paragraph("AI Data Analyst Report", style),
        Spacer(1, 20)
    ]


def build_dataset_overview(dataset):
    return [
        Paragraph("<b>Dataset Overview</b>", styles["Heading2"]),
        Spacer(1, 10),

        Paragraph(f"<b>File Name:</b> {dataset['file_name']}", styles["BodyText"]),
        Paragraph(f"<b>Rows:</b> {dataset['rows']}", styles["BodyText"]),
        Paragraph(f"<b>Columns:</b> {dataset['columns']}", styles["BodyText"]),
        Paragraph(f"<b>Business Type:</b> {dataset['business_type']}", styles["BodyText"]),

        Spacer(1, 20)
    ]


def build_business_summary(summary):
    return [
        Paragraph("<b>Business Summary</b>", styles["Heading2"]),
        Spacer(1, 10),

        Paragraph(summary, styles["BodyText"]),

        Spacer(1, 20)
    ]


def build_insights(insights):

    elements = [
        Paragraph("<b>Key Insights</b>", styles["Heading2"]),
        Spacer(1, 10)
    ]

    for insight in insights:
        elements.append(
            Paragraph(f"• {insight}", styles["BodyText"])
        )

    elements.append(Spacer(1, 20))

    return elements


def build_recommendations(recommendations):

    elements = [
        Paragraph("<b>Recommendations</b>", styles["Heading2"]),
        Spacer(1, 10)
    ]

    for recommendation in recommendations:
        elements.append(
            Paragraph(f"• {recommendation}", styles["BodyText"])
        )

    elements.append(Spacer(1, 20))

    return elements





def build_footer():
    return [
        Spacer(1, 30),
        Paragraph(
            "Generated by AI Data Analyst",
            styles["Italic"]
        )
    ]